#!/bin/bash

chosen=$(nmcli device wifi list | sed 's/\([0-9A-F]\{2\}:\)\{5\}[0-9A-F]\{2\}  //g;s/Infra  [0-9]\{1,3\}\ *//g;s/\(IN-USE\|BSSID\|MODE\|CHAN\)\ \+//g;s/^\*\ */* /g;s/^\ \+/  /g;s/^SSID/  SSID/g' | dmenu -l 10 -p "Available wifi:" )
printf "chosen = $chosen\n"
processed=$(echo $chosen | sed 's/[0-9]\{2,3\} Mbit.*//g;s/^\ \+//g;s/\ \+$//g')
printf "processed = ${processed}XYZ\n"
[ "$processed" = "" ] && printf "exit 0\n" && exit 0
password=$(sudo grep "^psk=" "/etc/NetworkManager/system-connections/$processed.nmconnection" | cut -d= -f2)
printf "Catched pass: $password\n"
if test -z "$password"; then
  nmcli device wifi connect "$processed" && password=$(echo | dmenu -p "Password ($processed):") && nmcli device wifi connect "$processed" password "$password" && notify-send "Successfully connected to $processed"
else
  nmcli device wifi connect "$processed" password "$password" && notify-send "Successfully connected to $processed using saved pass"
fi
