#!/bin/bash


read -r DaySlashMonth DayOfWeek <<< $(date +%d/%m\ %w)
## 日曜日、月曜日、火曜日、水曜日、木曜日、金曜日、土曜日
japanese() { \
  case "$1" in
    "0") JpnDayOfWeek="日"
      ;;
    "1") JpnDayOfWeek="月"
      ;;
    "2") JpnDayOfWeek="火"
      ;;
    "3") JpnDayOfWeek="水"
      ;;
    "4") JpnDayOfWeek="木"
      ;;
    "5") JpnDayOfWeek="金"
      ;;
    "6") JpnDayOfWeek="土"
      ;;
  esac
}
## Execute here once so that JpnDayOfWeek be created when startx.
japanese $DayOfWeek



DELIM="|"
status() { \
  TIME=$(date +%Hh%M)
  if [ "$Time" = "00h00" ] || [ "$Time" = "00h01" ]; then
    read -r DaySlashMonth DayOfWeek <<< $(date +%d/%m\ %w)
    japanese $DayOfWeek
  fi
  echo " $DaySlashMonth" "($JpnDayOfWeek)" "$TIME"
  echo "$DELIM"

  CAPACITY=$(cat /sys/class/power_supply/BAT0/capacity)
  BAT_STAT=$(cat /sys/class/power_supply/BAT0/status)
  echo $BAT_STAT $CAPACITY%
  echo "$DELIM"

  VOL=$(amixer get Master | awk -F'[][]' 'END{ print $4","$6 }' | sed 's/-\([0-9]\)\./-0\1\./;s/^0\./-00\./')

  if [ $(echo $VOL | cut -d "," -f 2) = "off" ]; then
    echo " Mute"
  else
    echo "$(echo $VOL | cut -d . -f 1)dB"
  fi
}

while :; do
  xsetroot -name "$(status | tr '\n' ' ')"
  sleep 1m
done
