#!/bin/bash

## Diff btw neofetch under Arch Linux and under Gentoo
## mac instead of macos


#DISTROS=(windows gentoo void arch ubuntu)
#for d in ${DISTROS[@]}
#do
#  clear
#  neofetch --ascii_distro $d
#  sleep 1
#done


#DISTROS=(AIX, Alpine, Anarchy, Android, Antergos, antiX, AOSC,
#Apricity,  ArcoLinux,  ArchBox,  ARCHlabs,  ArchStrike, XFerience, ArchMerge, Arch, Artix, Arya,
#Bedrock, Bitrig, BlackArch, BLAG, BlankOn, BlueLight, bonsai, BSD, BunsenLabs, Calculate, Carbs,
#CentOS, Chakra, ChaletOS, Chapeau, Chrome, Cleanjaro, ClearOS, Clear_Linux, Clover, Condres, Con‐
#tainer_Linux, CRUX, Cucumber, Debian, Deepin, DesaOS, Devuan, DracOS, DragonFly,  Drauger,  Ele‐
#mentary, EndeavourOS, Endless, EuroLinux, Exherbo, Fedora, Feren, FreeBSD, FreeMiNT, Frugalware,
#Funtoo, GalliumOS, Gentoo, Pentoo, gNewSense, GNU, GoboLinux, Grombyang,  Guix,  Haiku,  Huayra,
#Hyperbola,  janus,  Kali, KaOS, KDE_neon, Kibojoe, Kogaion, Korora, KSLinux, Kubuntu, LEDE, LFS,
#Linux_Lite, LMDE, Lubuntu, Lunar, mac, Mageia, MagpieOS, Mandriva, Manjaro, Maui, Mer,  Minix,
#LinuxMint,  MX_Linux,  Namib,  Neptune, NetBSD, Netrunner, Nitrux, NixOS, Nurunner, NuTyX, OBRe‐
#venge, OpenBSD, OpenIndiana, OpenMandriva, OpenWrt, osmc, Oracle, PacBSD, Parabola, Pardus, Par‐
#rot,  Parsix,  TrueOS,  PCLinuxOS,  Peppermint,  popos,  Porteus,  PostMarketOS, Proxmox, Puppy,
#PureOS, Qubes, Radix, Raspbian, Reborn_OS, Redstar, Redcore, Redhat,  Refracted_Devuan,  Regata,
#Rosa,  sabotage,  Sabayon, Sailfish, SalentOS, Scientific, Septor, SharkLinux, Siduction, Slack‐
#ware, SliTaz, SmartOS, Solus, Source_Mage, Sparky, Star, SteamOS,  SunOS,  openSUSE_Leap,  open‐
#SUSE_Tumbleweed,  openSUSE, SwagArch, Tails, Trisquel, Ubuntu-Budgie, Ubuntu-GNOME, Ubuntu-MATE,
#Ubuntu-Studio, Ubuntu, Void, Obarun, windows10, Windows7, Xubuntu, Zorin, IRIX,
#Arch_old, Ubuntu_old, Redhat_old, Dragonfly_old
#Lubuntu, Kubuntu, Xubuntu, Ubuntu-GNOME,
#Ubuntu-Studio, Ubuntu-Mate, Ubuntu-Budgie
#Arcolinux_small, Dragonfly_small, Fedora_small, Alpine_small, Arch_small, Ubuntu_small,
#CRUX_small,  Debian_small, Gentoo_small, FreeBSD_small, Mac_small, NixOS_small, OpenBSD_small, android_small, Antrix_small, CentOS_small, Cleanjaro_small, Elemen‐
#taryOS_small, GUIX_small, Hyperbola_small, Manjaro_small, MXLinux_small, NetBSD_small, Parabola_small, POP_OS_small, PureOS_small,  Slackware_small,  SunOS_small,
#LinuxLite_small, OpenSUSE_small, Raspbian_small, postmarketOS_small, Void_small)



DISTROS=(AIX Alpine Anarchy Android Antergos antiX AOSC
Apricity ArcoLinux ArchBox ARCHlabs ArchStrike XFerience ArchMerge Arch Artix Arya
Bedrock Bitrig BlackArch BLAG BlankOn BlueLight BSD BunsenLabs Calculate
CentOS Chakra ChaletOS Chapeau Chrome ClearOS Clover Condres
CRUX Debian Deepin DesaOS Devuan DracOS DragonFly Drauger Elementary Endless Exherbo Fedora FreeBSD FreeMiNT Frugalware
Funtoo GalliumOS Gentoo Pentoo gNewSense GNU GoboLinux Grombyang Haiku Huayra
Hyperbola Kali KaOS KDE_neon Kibojoe Kogaion Korora KSLinux Kubuntu LEDE
LMDE Lubuntu Lunar Mac Mageia MagpieOS Mandriva Manjaro Maui Mer Minix
LinuxMint MX_Linux Namib NetBSD Netrunner Nitrux NixOS Nurunner NuTyX OBRevenge OpenBSD OpenIndiana OpenMandriva OpenWrt osmc Oracle PacBSD Parabola Pardus Parrot Parsix TrueOS PCLinuxOS Peppermint Porteus PostMarketOS Puppy
PureOS Qubes Raspbian Reborn_OS Redstar Redcore Redhat Regata
Rosa sabotage Sabayon SalentOS Scientific SharkLinux Siduction Slackware SliTaz SmartOS Solus Sparky Star SteamOS SunOS openSUSE SwagArch Tails Trisquel Ubuntu-Budgie Ubuntu-GNOME Ubuntu-MATE
Ubuntu-Studio Ubuntu Void Windows10 Windows7 Xubuntu Zorin
Arch_old Ubuntu_old Redhat_old Dragonfly_old
Lubuntu Kubuntu Xubuntu Ubuntu-GNOME
Ubuntu-Studio Ubuntu-Mate Ubuntu-Budgie
#Arcolinux_small Dragonfly_small Fedora_small Alpine_small Arch_small Ubuntu_small CRUX_small Debian_small Gentoo_small FreeBSD_small Mac_small NixOS_small OpenBSD_small android_small CentOS_small ElementaryOS_small Hyperbola_small Manjaro_small MXLinux_small NetBSD_small Parabola_small PureOS_small Slackware_small Raspbian_small postmarketOS_small Void_small
)

#n_sec=0.5
n_sec=1.6

## Display each one of them, following the order
#echo ${DISTROS[@]}
#for d in ${DISTROS[@]}
#do
#  #clear
#  echo $d
#  neofetch --ascii_distro $d
#  sleep $n_sec
#done


## Display each one of them randomly
n_distros=${#DISTROS[@]}
#echo $n_distros
#echo $((RANDOM % $n_distros))
while :
do
  rand=$((RANDOM % $n_distros))
  clear
  printf "\n\n\n\n"
  neofetch --ascii_distro ${DISTROS[$rand]} | sed "s/[Gg]entoo/${DISTROS[$rand]}/g"
  #neofetch --ascii_distro ${DISTROS[$rand]} | sed "s/[Gg]entoo/${DISTROS[$rand]}/g;s/^/                    /"
  #neofetch --ascii_distro ${DISTROS[$rand]} | sed "s/[Gg]entoo/${DISTROS[$rand]}/g;s/^/ \{18\}/"
  sleep $n_sec
done
