#!/bin/bash

FOLDERs="/var/lib/connman"
#grep -Rn "Name=" | sed 's/.*Name=\(.*\)$/\1/'
greppes=$(sudo grep -Rn "Name=" $FOLDERs)
#printf "greppes = $greppes\n"
#SSIDs=$(echo $greppes | sed 's/.*Name=\(.*\)$/\1/')
SSIDs=$(printf "$greppes" | sed 's/.*Name=\(.*\)$/\1/')
#printf "SSIDs = $SSIDs\n"
ssid=$(printf "$SSIDs" | dmenu -l 20)
#file=$(sudo grep -Rn "Name=$ssid" $FOLDERs)
file=$(sudo grep -Rn "Name=$ssid" $FOLDERs | sed 's/\(^[^\:]\+\):.*/\1/')
printf "file = $file\n"
passphrase=$(sudo grep -Rn "Passphrase=" $file | sed 's/Passphrase=\(.*\)/\1/')
printf "$(sudo grep -Rn \"Passphrase=\" $file)"
notify-send "Password = \"$passphrase\""
