#!/bin/bash
#nmcli device wifi list | sed '/IN-USE/d;/\*/d' | awk '{print $1}' | dmenu -l 10
#nmcli device wifi list | sed '/IN-USE/d;/\*/d;s/Infra.*//g;s/^\s*//g' | dmenu -l 10
#chosen=$(nmcli device wifi list | sed '/IN-USE/d;/\*/d;s/Infra.*//g;s/^\s*//g;s/\s*$//g' | dmenu -l 10 -p "Available wifi:")
## For gentoo
#chosen=$(nmcli device wifi list | sed '/IN-USE/d;/\*/d;s/Infra.*//g;s/^\s*//g;s/\s*$//g' | awk '{print $2}' | dmenu -l 10 -p "Available wifi:")
## For arch linux
#chosen=$(nmcli device wifi list | sed '/IN-USE/d;/\*/d;s/Infra.*//g;s/^\s*//g;s/\s*$//g' | awk '{print $2}' | dmenu -l 10 -p "Available wifi:")
#nmcli device wifi list | sed '/IN-USE/d;/\*/d;s/Infra.*//g;s/.*:[0-9A-Z]\{2\}\s//g;s/^\s*//g;s/\s*$//g' 
#nmcli device wifi list | sed '/IN-USE/d;/\*/d;s/Infra.*//g;s/.*:[0-9A-Z]\{2\}\s\+//g;s/\s*$//g' 

#chosen=$(nmcli device wifi list | sed '/IN-USE/d;/\*/d;s/Infra.*//g;s/.*:[0-9A-Z]\{2\}\s\+//g;s/\s*$//g' | dmenu -l 10 -p "Available wifi:")

#################
## Old, worked ##
#################
#chosen=$(nmcli device wifi list | dmenu -l 10 -p "Available wifi:" | sed '/IN-USE/d;/\*/d;s/Infra.*//g;s/.*:[0-9A-Z]\{2\}\s\+//g;s/\s*$//g' )
#printf "chosen = $chosen\n"
#
#
###[[ "$chosen"="" || "$chosen"="\n" ]] && printf "exit 0\n" && exit 0
###[ "$chosen"="" || "$chosen"="\n" ] && printf "exit 0\n" && exit 0
#[ "$chosen" = "" ] && printf "exit 0\n" && exit 0
#if [[ "$chosen" = "Gia Nguyen"* ]]; then
#  password="khongcomatkhau"
#else
#  password=$(echo | dmenu -p "Password:")
#fi
#nmcli device wifi connect "$chosen" password "$password"


##############
## New Page ##
##############
if command -v nmcli &> /dev/null; then
  #chosen=$(nmcli device wifi list | dmenu -l 10 -p "Available wifi:" | sed 's/\([0-9A-F]\{2\}:\)\{5\}[0-9A-F]\{2\}  //g;s/Infra  [0-9]\{1,3\}\ *//g;s/\(IN-USE\|BSSID\|MODE\|CHAN\)\ \+//g;s/^\*\ */* /g;s/^\ \+/  /g;s/^SSID/  SSID/g')
  chosen=$(nmcli device wifi list | sed 's/\([0-9A-F]\{2\}:\)\{5\}[0-9A-F]\{2\}  //g;s/Infra  [0-9]\{1,3\}\ *//g;s/\(IN-USE\|BSSID\|MODE\|CHAN\)\ \+//g;s/^\*\ */* /g;s/^\ \+/  /g;s/^SSID/  SSID/g' | dmenu -l 10 -p "Available wifi:" )
  printf "chosen = $chosen\n"
  #processed=$(echo $chosen | sed 's/[0-9]\{2,3\} Mbit.*//g;s/^\ +//g')
  processed=$(echo $chosen | sed 's/[0-9]\{2,3\} Mbit.*//g;s/^\ \+//g;s/\ \+$//g')
  SSID=$(echo $chosen | sed 's/[0-9]\{2,3\} Mbit.*//g;s/^\ \+//g;s/\ \+$//g')
  printf "processed = ${processed}XYZ\n"
  #[ "$chosen" = "" ] && printf "exit 0\n" && exit 0
  #if [[ "$chosen" = "Gia Nguyen"* ]]; then
  #  password="khongcomatkhau"
  #else
  #  password=$(echo | dmenu -p "Password:")
  #fi
  #nmcli device wifi connect "$chosen" password "$password"
elif command -v connman &> /dev/null; then
  echo connman exists on your machine
else
  echo None of nmcli, connmanctl exists on your machine. Consider installing them before using this script.
fi





#if command -v nmcli &> /dev/null; then
#  echo nmcli exists on your machine
#elif command -v connman &> /dev/null; then
#  echo connman exists on your machine
#else
#  echo None of nmcli, connmanctl exists on your machine. Consider installing them before using this script.
#fi



